services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    env_file:
      - comp-networks.env
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  mongo_data:
